---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
    - name: Port Open 22
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp
    - name: Port Open 8001
      community.general.ufw:
        rule: allow
        port: '8001'
        proto: tcp

