name: Build PetClinic

on:
  workflow_dispatch:

jobs:
  agentcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up JDK 8
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        id: build_with_maven
        run: |
          mvn clean package -DskipTests

